# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: atlas-cli-plugin-terraform

version: 2

before:
  hooks:
    - go mod tidy
    - curl https://pgp.mongodb.com/atlas-cli.asc -o atlas-cli.asc

builds:
  - id: linux
    goos: [linux]
    <<: &build_defaults
      binary: ./binary
      main: ./cmd/plugin
  - id: macos
    goos: [darwin]
    <<: *build_defaults
    hooks:
      # This will notarize Apple binaries and replace goreleaser bins with the notarized ones
      post:
        - cmd: ./scripts/mac_notarize.sh
          output: true
  - id: windows
    goos: [windows]
    <<: *build_defaults
    hooks:
      # This will notarize the Windows binary and replace goreleaser bin with the notarized one
      post:
        - cmd: ./scripts/windows_notarize.sh
          output: true

archives:
  - id: linux
    builds: [linux]
    <<: &archive_defaults
      files:
        - src: './bin/manifest{{ if eq .Os "windows" }}.windows{{end}}.yml'
          dst: ./manifest.yml
  - id: macos
    builds: [macos]
    <<: *archive_defaults
  - id: windows
    builds: [windows]
    <<: *archive_defaults

signs:
  - id: all_artifacts
    signature: "${artifact}.sig"
    cmd: "./scripts/notarize.sh"
    ids:
      - linux
      - macos
      - windows
    artifacts: all
    output: true

release:
  prerelease: auto
  extra_files:
    - glob: ./*.asc
