# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: atlas-cli-plugin-terraform

version: 2

before:
  hooks:
    - go mod tidy
    - curl https://pgp.mongodb.com/atlas-cli.asc -o atlas-cli.asc

builds:
  - id: linux
    goos: [linux]
    goarch: [amd64, arm64]
    <<: &build_defaults
      binary: ./binary
      main: ./cmd/plugin
      goamd64: [v1]
      goarm64: [v8.0]
  - id: macos
    goos: [darwin]
    goarch: [amd64, arm64]
    <<: *build_defaults
    hooks:
      # This will notarize Apple binaries and replace goreleaser bins with the notarized ones
      post:
        - cmd: ./scripts/mac_notarize.sh
          output: true
          env:
            - artifact="{{ .Path }}"

  - id: windows
    goos: [windows]
    goarch: [amd64]
    <<: *build_defaults
    hooks:
      # This will notarize the Windows binary and replace goreleaser bin with the notarized one
      post:
        - cmd: ./scripts/windows_notarize.sh
          output: true
          env:
            - artifact="{{ .Path }}"

archives:
  - id: linux
    builds: [linux]
    <<: &archive_defaults
      files:
        - src: './bin/manifest{{ if eq .Os "windows" }}.windows{{end}}.yml'
          dst: ./manifest.yml
  - id: macos
    builds: [macos]
    <<: *archive_defaults
  - id: windows
    builds: [windows]
    <<: *archive_defaults

signs:
  - id: all_artifacts
    signature: "${artifact}.sig"
    cmd: "./scripts/notarize.sh"
    ids:
      - linux
      - macos
      - windows
    artifacts: all
    output: true

release:
  prerelease: auto
  extra_files:
    - glob: ./*.asc

gomod: # https://goreleaser.com/customization/verifiable_builds/
  # Proxy a module from proxy.golang.org, making the builds verifiable.
  # This will only be effective if running against a tag. Snapshots will ignore
  # this setting.
  # Notice: for this to work your `build.main` must be a package, not a `.go` file.
  proxy: false
  # Sets the `-mod` flag value.
  #
  # Since: v1.7
  mod: mod
